# Generated by Django 4.0.5 on 2022-06-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='slug',
            new_name='identifier',
        ),
    ]
